[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
sycamore = { version = "0.8.2", features = ["hydrate" , "suspense"] }
sycamore-router = "0.8.0"
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
log = "0.4.17"
web-sys = "0.3.61"

